version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    macos:
      xcode: 10.2.1
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run: 
          name: Carthage
          command: |
            brew install carthage
            carthage bootstrap --platform ios
      - run:
          name: XCodeGen
          command: |
            curl -L https://github.com/yonaskolb/XcodeGen/releases/download/2.6.0/xcodegen.zip -o a.zip
            unzip a.zip
            ./xcodegen/install.sh
            xcodegen
      - run:
          name: Test
          command: |
            touch user.xcconfig
            make test | xcpretty
      - codecov/upload
