version: 2.1

jobs:
  build:
    macos:
      xcode: 10.2.1
    steps:
      - checkout
      - run: |
          git submodule init
          git submodule update
      - restore_cache:
          key: carthdeps
      - run: 
          name: Carthage
          command: |            
            carthage version
            swift -version
            carthage bootstrap --platform ios
      - save_cache:
          key: carthdeps
          paths:
            - ~/project/Carthage
            - ~/Library/Caches/org.carthage.CarthageKit
      - run:
          name: XCodeGen
          command: |
            curl -L https://github.com/yonaskolb/XcodeGen/releases/download/2.6.0/xcodegen.zip -o a.zip
            unzip a.zip
            ./xcodegen/install.sh
            xcodegen
      - run:
          name: Test
          command: |
            touch user.xcconfig
            make test | xcpretty
      - run:
          name: Codecov.io
          command: |
            curl -s https://codecov.io/bash | bash -s -- \
                -t "${CODECOV_TOKEN}" \
                -n "${CIRCLE_BUILD_NUM}" \
                -y "./codecov.yml" \
                -J "BitriseClient" \
                -Z || echo 'Codecov upload failed'
